server:
  port: 8081
  connection-timeout: 30000
  servlet.session.timeout: 120m
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
    accesslog:
      enabled: true
      prefix: "access.log"
      suffix: ""
      pattern: "%{request.id}r %{yyyy-MM-dd HH:mm:ss.SSS}t|%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b\t%D"
    basedir: "${user.home}/app"
  error:
    whitelabel:
      enabled: false

# Mysql recommended settings
dataSource:
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  main:
    allow-bean-definition-overriding: true
  security:
    basic:
      enabled: false
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: false
  mvc:
    async:
      request-timeout: 30000

logging:
  level:
    org.springframework.boot.autoconfigure: debug

# default
---
spring:
  profiles: default
  profiles.active: ${PROFILE:dev}

# dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://database-1.cnkn0rxloz7j.ap-northeast-2.rds.amazonaws.com:3306/hisc?useSSL=false
    username: hisc
    password: hisc123!
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

truedoc:
  static.location: file:/root/app/media/

elasticsearch:
  url: localhost
  port: 9200

logging:
  level:
    com.zaxxer.hikari: info
    org.hibernate.type: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
debug: true
